services:
  gin-server:
    build: .
    ports:
      - "8088:8088"
    restart: always
    volumes:
      - .:/app
    environment:
      - GIN_MODE=release

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tracks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
    ports:
      - "5432:5432"