// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/getsong": {
            "post": {
                "description": "Возвращает информацию о музыкальном треке по переданной ссылке.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "songs"
                ],
                "summary": "Получение информации о треке",
                "parameters": [
                    {
                        "description": "JSON URL трека",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.GetSongRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о треке",
                        "schema": {
                            "$ref": "#/definitions/trackinfo.TrackInfo"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/trackinfo.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Трек не найден",
                        "schema": {
                            "$ref": "#/definitions/trackinfo.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.GetSongRequest": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://music.apple.com/song/697195787"
                }
            }
        },
        "trackinfo.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "trackinfo.TrackInfo": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "artist": {
                            "type": "string"
                        },
                        "cover_url": {
                            "type": "string"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "links": {
                            "type": "object",
                            "properties": {
                                "apple_music_url": {
                                    "type": "string"
                                },
                                "deezer_url": {
                                    "type": "string"
                                },
                                "spotify_url": {
                                    "type": "string"
                                },
                                "vk_music_url": {
                                    "type": "string"
                                },
                                "yandex_music_url": {
                                    "type": "string"
                                }
                            }
                        },
                        "preview": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
